<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_2836 Coral</name>
   <tag></tag>
   <elementGuidId>a78e4845-edfd-4c60-bf3c-5cd45e31905d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id = 'PlacesAutocomplete__suggestion-ChIJQfYmp1oF2YgRWUCxV1G5MTU' and (text() = '2836 Coral Springs Drive, Coral Springs, FL, USA' or . = '2836 Coral Springs Drive, Coral Springs, FL, USA')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='PlacesAutocomplete__suggestion-ChIJQfYmp1oF2YgRWUCxV1G5MTU']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>suggestion-item--active</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PlacesAutocomplete__suggestion-ChIJQfYmp1oF2YgRWUCxV1G5MTU</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2836 Coral Springs Drive, Coral Springs, FL, USA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;main-app&quot;]/div[@class=&quot;pt-4&quot;]/div[@class=&quot;fullLoader secondbg pt-5&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;checkout-conatiner&quot;]/div[@class=&quot;row purchase-details secondbg&quot;]/div[@class=&quot;col-lg-4 billing&quot;]/div[@class=&quot;billing-address-text p-md-4 p-3 shadow checkout-shadow-color-padding&quot;]/div[@class=&quot;collapse show&quot;]/div[1]/div[5]/div[@class=&quot;row frm-details&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;has-input&quot;]/div[1]/div[@class=&quot;autocomplete-dropdown-container&quot;]/div[@id=&quot;PlacesAutocomplete__suggestion-ChIJQfYmp1oF2YgRWUCxV1G5MTU&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='PlacesAutocomplete__suggestion-ChIJQfYmp1oF2YgRWUCxV1G5MTU']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div[5]/div/div/div/div/div[2]/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Your Address'])[1]/following::div[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Address*'])[1]/following::div[15]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/preceding::div[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/preceding::div[7]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div[2]/div</value>
   </webElementXpaths>
</WebElementEntity>
