<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_1</name>
   <tag></tag>
   <elementGuidId>13db9faa-22a9-48f5-a2e8-6b7d524d238c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div/div[1]/div/div/div/div[2]/div/div/div[2]/div/form/div[3]/div[2]/div[1]/div[2]/div/i[4]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[@class=&quot;cart-has-item modal-open&quot;]/div[4]/div[1]/div[@class=&quot;modal fade show&quot;]/div[@class=&quot;modal-dialog full-screen-modal&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;Modal-body full-screen-modal-body&quot;]/div[@class=&quot;modal-inner&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;flex-column align-items-center position-relative  d-flex h-100 justify-content-center&quot;]/div[@class=&quot;add-review-wrapper&quot;]/div[@class=&quot;add-review-inner&quot;]/form[1]/div[@class=&quot;row pt-3&quot;]/div[@class=&quot;row w-100&quot;]/div[@class=&quot;col-lg-4&quot;]/div[@class=&quot;mb-3 w-100&quot;]/div[@class=&quot;stars&quot;]/i[4]/svg[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>currentColor</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>18</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>18</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 16 16</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;cart-has-item modal-open&quot;]/div[4]/div[1]/div[@class=&quot;modal fade show&quot;]/div[@class=&quot;modal-dialog full-screen-modal&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;Modal-body full-screen-modal-body&quot;]/div[@class=&quot;modal-inner&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;flex-column align-items-center position-relative  d-flex h-100 justify-content-center&quot;]/div[@class=&quot;add-review-wrapper&quot;]/div[@class=&quot;add-review-inner&quot;]/form[1]/div[@class=&quot;row pt-3&quot;]/div[@class=&quot;row w-100&quot;]/div[@class=&quot;col-lg-4&quot;]/div[@class=&quot;mb-3 w-100&quot;]/div[@class=&quot;stars&quot;]/i[4]/svg[1]</value>
   </webElementProperties>
</WebElementEntity>
