<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_category</name>
   <tag></tag>
   <elementGuidId>1efa7015-cc37-4e1b-83f6-35ce0647a6a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//li//*[contains(@href,'category')])[${category}]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
